# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-25 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='testmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_ID', models.CharField(max_length=12)),
                ('model_NAME', models.CharField(max_length=20)),
                ('model_PASSWORD', models.CharField(max_length=32)),
            ],
        ),
    ]
